on:
  - push

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_TOKEN}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:latest

  update_variable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - uses: docker/login-action@v3
#        with:
#          username: ${DOCKER_USERNAME}
#          password: ${DOCKER_TOKEN}

      - name: pull image
        run: docker pull ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:latest

      - name: run container
        run: |
          docker run \
          -e KEY=key \
          -e VALUE=value \
          -e TARGET_ENVIRONMENT=production \
          -e VARIABLE_TYPE=plain \
          -e COMMENT=gha \
          ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}