on:
  - push

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

  update_variable:
    runs-on: ubuntu-latest

    needs: build_image

    steps:
      - uses: actions/checkout@v4

#      - uses: docker/login-action@v3
#        with:
#          username: ${DOCKER_USERNAME}
#          password: ${DOCKER_TOKEN}

      - name: pull image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: run container
        run: |
          docker run \
          -e KEY=key \
          -e VALUE=value \
          -e TARGET_ENVIRONMENT=production \
          -e VARIABLE_TYPE=plain \
          -e COMMENT=gha \
          -e VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
          -e VERCEL_TEAM_ID=${{ secrets.VERCEL_TEAM_ID }} \ 
          -e VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}