on:
  - push

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

  update_variable:
    runs-on: ubuntu-latest

    needs: build_image

    steps:
      - uses: docker://joshdirkx/vercel_environment_updater
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          KEY: key
          VALUE: value
          TARGET_ENVIRONMENT: production
          VARIABLE_TYPE: plain
          COMMENT: gha